import { AboutStyle } from "@/styles/about";
import React from "react";
import Image from "next/image";
import { Aboutt, Frame2, Team1, Team2, Team3, Team4 } from "../../public/image";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>Rhivet-about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutStyle>
        <section>
          <div className="circle"></div>
          <h4>About Us</h4>
          <h1>Hi, We’re Rhivet Networks</h1>
          <p className="p">
            At Rhivet Networks, we are passionate about protecting businesses
            and individuals from evolving cyber threats. With years of
            experience and a team of dedicated experts, we deliver cutting-edge
            cybersecurity solutions tailored to your specific needs. Learn more
            about our journey and commitment to safeguarding your digital
            assets.
          </p>
          <div className="img">
            <Image src={Aboutt} alt="img" />
          </div>
          <div className="story">
            <div>
              {/* <h5>How it Started</h5> */}
              <h2>Our mission</h2>
            </div>
            <div className="text">
              <p>
                Providing unmatched cybersecurity solutions that protect and
                fortify our clients against evolving cyber threats. We are
                dedicated to empowering our clients to navigate the complex
                cybersecurity landscape, ensuring their valuable assets,
                reputation, and future remain secure.
              </p>
            </div>
          </div>
          <div className="team">
            <h4>Rhivet Team</h4>
            <h2>Meet the team</h2>
            <div className="image__team">
              <Image src={Team1} alt="img" />
              <Image src={Team2} alt="img" />
              <Image src={Team3} alt="img" />
              <Image src={Team4} alt="img" />
            </div>
          </div>
        </section>
      </AboutStyle>
    </>
  );
};

export default About;
